package com.Travedia.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import gui.Login;
import gui.PaiementHomeForm;
import gui.ProfileForm;
import gui.ReclamationHomeForm;
import gui.SessionManager;
import gui.SignUpForm;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Travedia {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        ReclamationHomeForm recHomeForm= new ReclamationHomeForm();
        PaiementHomeForm payHomeForm= new PaiementHomeForm();
         
        //recHomeForm.show();
        //payHomeForm.show();
        //new ListRegionForm(theme).show();
        //new Login(theme).show();
         if(SessionManager.getNom()==null) {
            
       
        //awel interface besh tethaal
        new Login(theme).show(); //nhotou signup besh tji awel form
        //new SignInForm(theme).show();
         }
        else {
            new ProfileForm(theme).show();
        }
        //new AjoutCategorie(theme).show();
        //System.out.println(ReclamationController.getInstance().getAllReclamation().get(0).getContenu());
        //Reclamation r = ReclamationController.getInstance().getAllReclamation().get(1);
       // r.setContenu("Again This is Contenu Test");
       // r.setEtat_reclamation("En Cours");
       // r.setUser_id(1);
        
        //System.out.println( ReclamationController.getInstance().ajouterReclamation(r));
            //System.out.println( ReclamationController.getInstance().modifierReclamation(r));
            //System.out.println(ReclamationController.getInstance().Delete(r.getId()));

    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
